---
- name: Add blender PPA
  become: yes
  become_method: sudo
  apt_repository:
    repo: ppa:thomas-schiex/blender

- name: Update cache
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    state: present

- name: Install blender
  become: yes
  become_method: sudo
  apt: name=blender state=present
