---
- hosts: all
  pre_tasks:
    - name: Update homebrew
      homebrew:
        update_homebrew: yes
        upgrade_all: yes

  roles:
    - terminal-mac
    - python-mac
    - nodejs-mac
    - docker-mac
    - tools-mac

  vars:
    python_3_version: 3.10.2
    nodejs_version: 17.4.0
