---
- hosts: all
  tasks:
    - name: Add NeoVim PPA
      become: yes
      become_method: sudo
      apt_repository:
        repo: 'ppa:neovim-ppa/stable'

    - name: Add Numix PPA
      become: yes
      become_method: sudo
      apt_repository:
        repo: 'ppa:numix/ppa'

    - name: Update cache
      become: yes
      become_method: sudo
      apt:
        update_cache: yes
        state: present

    - name: Install base pacakges
      become: yes
      become_method: sudo
      apt: name={{item}} state=present
      with_items:
        - openjdk-8-jdk
        - gradle
        - postgresql
        - xclip
        - powerline
        - curl
        - tree
        - git
        - tmux
        - zsh
        - neovim
        - numix-gtk-theme
        - nodejs-legacy
        - npm

    - name: Install Vim-Plug
      shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: Install Tmux plugin manager (tpm)
      git:
        repo: 'https://github.com/tmux-plugins/tpm'
        dest: ~/.tmux/plugins/tpm

    - name: Install Oh My ZSH
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      become: yes
      become_method: sudo

    - name: Download bullet train ZSH theme
      shell: curl -o ~/.oh-my-zsh/themes/bullet-train.zsh-theme https://raw.githubusercontent.com/caiogondim/bullet-train-oh-my-zsh-theme/master/bullet-train.zsh-theme

    - name: Enable ZSH
      shell: chsh -s $(which zsh)
      become: yes
      become_method: sudo

    - name: Set up node_modules global cache.
      shell: mkdir -p ~/.npm-global && chown -R $(whoami) ~/.npm-global && chown -R $(whoami) ~/.npm

    - name: Update Node and Npm
      shell: npm install -g npm && npm install -g n && n stable
      environment:
        NPM_CONFIG_PREFIX: ~/.npm-global

    - name: Install node packages
      shell: npm i -g elm
      environment:
        NPM_CONFIG_PREFIX: ~/.npm-global

    - name: Autoremove
      become: yes
      become_method: sudo
      apt:
        autoremove: yes
