---
- name: Install VS Code
  homebrew_cask:
    name: visual-studio-code
    state: present

- name: Install Firefox
  homebrew_cask:
    name: firefox
    state: present

- name: Install Spectacle
  homebrew_cask:
    name: spectacle
    state: present
