---
- name: Install Python3 pacakges
  become: yes
  become_method: sudo
  apt: name={{item}} state=present
  with_items:
    - python3.5
    - python3-pip
    - python3-dev

# More info here: https://github.com/pyenv/pyenv-installer
- name: Install pyenv
  shell: curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash

- name: Install latest python version
  shell: pyenv install {{ python_3_version }} -s

- name: Set global system python version
  shell: pyenv global {{ python_3_version }}

# Updates pyenv
- name: Update pyenv
  shell: pyenv update

- name: Install Pip3 packages
  become: yes
  become_method: sudo
  pip: name={{item}} state=latest executable=/home/shane/.pyenv/shims/pip
  with_items:
    - neovim
    - flake8
    - vulture
