---
- name: Install NodeJS pacakges
  homebrew:
    name: node
    state: present

- name: Update Node and Npm
  shell: npm install -g npm && npm install -g n && n {{ nodejs_version }}
  become: yes


- name: Install NPM packages
  npm: name={{item}} global=yes
  with_items:
    - yarn
    - create-react-app
    - tern
    - typescript
